repos:
-   repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
    -   id: black
        language_version: python3
        args: [--line-length=88]

-   repo: https://github.com/pycqa/pylint
    rev: v3.0.0
    hooks:
    -   id: pylint
        additional_dependencies: [pylint-django] 