mcp:
  servers:
    cli:
      command: "uvx"
      args: ["cli-mcp-server"]
      env:
        ALLOWED_DIR: "/Users/zaidalsaheb/projects/mcp-client/agent_workspace"
        ALLOWED_COMMANDS: "all"
        ALLOWED_FLAGS: "all"
        MAX_COMMAND_LENGTH: "1024"
        COMMAND_TIMEOUT: "300"
        GITHUB_API_KEY: "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"
        EXAMPLE_REPO_URL: "https://github.com/deploypilotorg/example-repo"
        ALLOW_SHELL_OPERATORS: "true"
        GIT_TERMINAL_PROMPT: "0"
        GIT_ASKPASS: "/bin/echo"
    docker-mcp:
      command: "uvx"
      args: ["docker-mcp"]

clients:
  # Default model, when no model specified
  default:
    provider: "anthropic"
    model: "sonnet"
  
  # Different models can be specified with --model flag
  sonnet:
    provider: "anthropic"
    model: "sonnet"
  
  mini:
    provider: "anthropic"
    model: "haiku"