name: Check Requirements

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  check-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Get explicitly installed packages
        id: installed-packages
        run: |
          # Get only explicitly installed packages (not dependencies)
          pip list --not-required --format=freeze > installed_packages.txt
          echo "INSTALLED_PACKAGES=$(cat installed_packages.txt)" >> $GITHUB_ENV
          
      - name: Compare with requirements.txt
        run: |
          # Get packages from requirements.txt
          grep -v '^#' requirements.txt | cut -d'=' -f1 | sort > requirements_packages.txt
          
          # Get packages from installed packages
          grep -v '^#' installed_packages.txt | cut -d'=' -f1 | sort > installed_packages_clean.txt
          
          # Find packages that are installed but not in requirements.txt
          comm -23 installed_packages_clean.txt requirements_packages.txt > missing_packages.txt
          
          if [ -s missing_packages.txt ]; then
            echo "The following packages are installed but not listed in requirements.txt:"
            cat missing_packages.txt
            echo "Please update requirements.txt with the missing packages."
            exit 1
          fi 